#!/usr/bin/env bash
# Installs and configures Nginx with custom settings

# Update the package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create directories and files using echo
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create a custom Nginx configuration file using echo
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
