#!/bin/bash
# A shell script that configures the servers so that they have the same configurations.

# Update the package list and upgrade installed packages
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Allow incoming HTTP traffic (port 80) using ufw
sudo ufw allow 80/tcp

# Create a custom Nginx configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Create a symbolic link to enable the default configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Create the default HTML file with your content
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Create the custom 404.html file with the message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx

# Enable and start Nginx at boot
sudo systemctl enable nginx
sudo systemctl start nginx

# Clean up
sudo apt autoremove -y

