#!/usr/bin/env bash
# A bash script that pings the ip address given as an argument.

# Check if an argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address="$1"

# Perform the ping 5 times
ping -c 5 "$ip_address"
