#!/usr/bin/env bash
# Finding out what keeps nginx from listening to port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | tail -n 1)"
