#!/usr/bin/env bash
# shorter version of making sure nginx always listens to port 80

# Remove the default site configuration in sites-enabled (if it exists)
rm -f /etc/nginx/sites-enabled/default

# Create a symbolic link from sites-available to sites-enabled
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Stop and start Nginx to apply the changes
nginx -s stop
nginx
