#!/bin/env bash
# A  Bash script that displays the content of the file /etc/passwd.

# Use IFS to set the delimiter to ':' for reading fields from the file
while IFS=':' read -r username uid _ _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "-------------------"
done < "/etc/passwd"

