#!/usr/bin/env bash
# This script will display "Best School" 10 times using while loop.

count=0

while [[ $count -lt 10 ]]; do
    if [ "$count" -eq 3 ]; then
        echo "bad luck"
    elif [ "$count" -eq 7 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count += 1))
done
