#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

count=0

while [[ $count -lt 20 ]]; do
    case "$((count + 1))" in
        4)
            echo "$((count + 1))"
            echo "bad luck from China"
            ;;
        9)
            echo "$((count + 1))"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$((count + 1))"
            echo "bad luck for Italy"
            ;;
        *)
            echo "$((count + 1))"
            ;;
    esac
    ((count++))
done
