#!/usr/bin/env bash
# a Bash script that displays The content of the current directory

# Loop through the files in the current directory
for file in *; do

  # Check if the file is not hidden 
  if [[ ! "$file" =~ ^\..* ]]; then

    # Get the part of the name after the first dash
    name="${file#*-}"

    # Display the modified name
    echo "$name"
  fi
done

