#!/usr/bin/env bash

#  RSA key pair.Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

private_key="school"
passphrase="betty"

ssh-keygen -t rsa -b 4096 -f $private_key -N "$passphrase"
